{%verbatim%}
				<!-- service-bottom -->
					<div id="about" class="service-bottom"  ng-if="islogin">
					<div class="container">
						<div class="smith">
							<div class="service-bottom-left">
								<img src="images/avatar-blank.png" alt=" " />
							</div>
							<div class="service-bottom-right">
								<h2>{{u.username}}</h2>
								<h3>{{org.name}}</h3>
								<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit,
								sed do eiusmod <span>tempor incididunt ut labore et dolore magna aliqua.
								Ut enim ad minim</span> veniam, quis nostrud exercitation ullamco laboris
								nisi ut aliquip ex ea com-<span>modo consequat. Duis aute irure dolor in 
								reprehenderit in voluptate velit esse</span> cillum dolore eu 
								fugiat nulla pariatur anim id est laborum</p>
								<div class="banner1-icons">
									<ul>
										<li><a href="#" class="facebook1"> </a></li>
										<li><a href="#" class="twitter1"> </a></li>
										<li><a href="#" class="in1"> </a></li>
									</ul>
									<button class="flowtobutton" ng-click="logout();">Logout</button>
								</div>
								<div class="bar">
									<p>PICS</p>
								</div>
								<div class="bar1">
									<p>84%</p>
								</div>
								<div class="clearfix"> </div>
								<div class="skills">
									 <div class="skill1" style="width:75%"> </div>							
								</div>

							</div>
							<div class="clearfix"> </div>
						</div>
					</div>
					</div>
				<!-- //service-bottom -->
{%endverbatim%}


