{%verbatim%}
<center><a class="flowtobutton" href="preview.html"><img src="images/ic_camera_alt_black_48dp.png"> Take a FLOWTO </a></center>
<div style="clear:both;"></div>
<!--user dashboard-->
<img src="images/dashboard.png">
<strong>{{u.username}}</strong>
<div style="clear:both;"></div>
Curent Assignment:[asignment] 
<div style="clear:both;"></div>
<div class="col-md-4">
<h1>Your ASSIGNMENTs</h1>
<a href="#"><h2><span>12</span></h2></a>
Assignments
<p>curent Assignment:UNKNOWN </p>
</div>
<div class="col-md-4">
<h1>Your FLOWTOs</h1>
<h2>50</h2>
FLOWTOs
</div>
<div style="clear:both;"></div>
<button ng-click="preview($event);">preview</button>
{%endverbatim%}


