{%verbatim%}
<div layout-align="center center" layout="row"><a class="flowtobutton" href="preview.html"><img src="images/ic_camera_alt_black_48dp.png"> Take a FLOWTO </a></div>
<!--user dashboard-->
<div layout="row" layout-wrap layout-align="left top">
	<div flex-gt-xs="55" flex-xs="100" layout="column" >
		<h2>{{assignmentName}}</h2>
		<p>your current assigment</p>
	</div>
	<div flex-gt-xs="5" hide-xs><!--blank//--></div>
	<div flex-gt-xs="40" flex-xs="100" layout="column" >
		<h2><span>{{assignmentNum}}</span><small>/{{assignmentTotal}}</small></h2>
		<p>FLOWTOs</p>
	</div>
</div>
{%endverbatim%}


