{%verbatim%}
<center><a class="flowtobutton" href="preview.html"><img src="images/ic_camera_alt_black_48dp.png"> Take a FLOWTO </a></center>
<div style="clear:both;"></div>
<!--user dashboard-->
<div layout="row">
	<div flex="55" flex-xs="100">
		<h1>{{assignmentName}}</h1>
		<p>assigment</p>
	</div>
	<div flex-gt-xs="5" hide-xs><!--blank//--></div>
	<div flex="40" flex-xs="100">
		<h1><span>{{assignmentNum}}</span><small>/{{assignmentTotal}}</small></h1>
		<p>FLOWTOs</p>
	</div>
</div>

{%endverbatim%}


